#!/bin/bash

##
# This script does an rsync of specific directories to the backup server (snap).
# This is *NOT* meant as a full backup solution. The proxmox server does full
# block level backups but these should *never* be needed. These backups are only
# meant to handle server data because salt should be used to re-deploy a server
# that was lost.
##

# [...]
# https://michael.lustfield.net/linux/long-term-secure-backups
